src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Utilisateur $user_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUserId(): ?Utilisateur
    {
        return $this->user_id;
    }

    public function setUserId(?Utilisateur $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
class Utilisateur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $prenom = null;

    #[ORM\Column(length: 20)]
    private ?string $nom = null;

    #[ORM\OneToMany(mappedBy: 'user_id', targetEntity: Article::class)]
    private Collection $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function __toString(){
        return $this->prenom;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setUserId($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getUserId() === $this) {
                $article->setUserId(null);
            }
        }

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Utilisateur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('content', TextareaType::class, [
                'label' => "Contenu",
                "attr" => [
                    "placeholder" => "Contenu de l'article"
                ]
            ])
            ->add('user_id', EntityType::class, [
                "label" => "Auteur",
                "class" => Utilisateur::class
                // ,
                // "choice_label" => function($user){
                //     return $user->getNom();
                // }
            ])
            ->add("Ajouter", SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    #[Route('/', name: 'app_article')]
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    //public function show(Article $article, $id, ArticleRepository $articleRepository)
    #[Route('/article/{id}', name: 'app_article_show')]
    public function show(Article $article){
        return $this->render("article/show.html.twig", ["article" => $article]);
    } 
    
    #[Route('/new/article', name: 'app_article_new')]
    public function new(Request $request, ArticleRepository $articleRepository){

        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);

        //reception du formulaire
        $form->handleRequest($request);
        if( $form->isSubmitted() && $form->isValid() ){
            $article->setCreatedAt(new \DateTimeImmutable());

            $articleRepository->save($article, true);   

            $this->addFlash("success", "L'article est bien ajouté ! ");
       
            return $this->redirectToRoute('app_article');
        }

        return $this->render("article/new.html.twig", [
            "form" => $form->createView()
        ]);
    }
}

src/Controller/UtilisateurController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateur;
use App\Repository\ArticleRepository;
use App\Repository\UtilisateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UtilisateurController extends AbstractController
{
    #[Route('/utilisateur', name: 'app_utilisateur')]
    public function index(ArticleRepository $articleRepo): Response
    {
        $articles = $articleRepo->findAll();
        return $this->render('utilisateur/index.html.twig', [
            "articles" => $articles
        ]);
    }
}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles{% endblock %}

{% block body %}
    <h2>Accueil</h2>

     {% for article in articles %}
          <div class="my-1">
               <a href="{{ path('app_article_show', {'id': article.id}) }}">
                    {{ article.titre }}
               </a>
               <div>{{ article.content | slice(0, 15)  }}...</div>
               Rédigé par 
               <strong>{{ article.userId.prenom ~ " " ~ article.userId.nom }}</strong>
               {{ article.createdAt | format_datetime(locale='fr') }}
          </div>
     {% endfor %}
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h2>new Article</h2>

    {{ form_start(form) }}
        
    {{ form_end(form) }}


{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h2>Article</h2>

     <div>{{ article.titre }}</div>
     <div>{{ article.content }}</div>
     Rédigé par 
     <strong>{{ article.userId.prenom ~ " " ~ article.userId.nom }}</strong>
     {{ article.createdAt | format_datetime(locale='fr') }}


     

{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        <header class="bg-secondary p-5">
            <h1 class="text-white text-center">
                <a href="{{ path('app_article') }}">Encore un blog</a>
            </h1>
            <nav class="text-end">
                <a href="{{ path('app_article_new') }}" class="text-white">New Article</a>
            </nav>
        </header>        
        <main class="container-fluid">

            {# Messages flash #}
            <div class="w-100 text-center">
                {% for message in app.flashes("success") %}
                    <div class="alert alert-success"> {{ message }} </div>
                {% endfor %}
            </div>
            {% block body %}{% endblock %}
        </main>
    </body>
</html>

templates/utilisateur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} user !{% endblock %}

{% block body %}

     

{% endblock %}